# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pr:
  branches:
    include:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string

#pr: none

trigger:
  branches:
    include:
      - master

resources:
  - repo: self

variables:
  - name: IMAGE
    value: splitman2e2e
  - name: tag
    value: '$(Build.BuildId)'

stages:
  - stage: Run_E2E
    displayName: Build E2E image
    jobs:
      - job: Run_E2E
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            inputs:
              command: build
              dockerfile: '**/Dockerfile_e2e'
              tags: |
                $(tag)
              arguments: '--build-arg IP="splitman2.fr:8081" -t $(IMAGE)'
            displayName: Build E2E image

          - script: |
              docker save "$IMAGE" -o "$(Build.ArtifactStagingDirectory)/$IMAGE.tar"
              #cp "SplitMan2-run/setup_azure_ssh.sh" "$(Build.ArtifactStagingDirectory)/"
            displayName: 'Save E2E image'

          - publish: '$(Build.ArtifactStagingDirectory)/$(IMAGE).tar'
            displayName: 'Publish tar image'
            artifact: $(IMAGE)_tar

#          - script: |
#              docker run splitman2_e2e
#            displayName: 'Run E2E image'
