# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

pool:
  vmImage: ubuntu-latest

stages:
#  - stage: Prepare
#    jobs:
#      - job: Prepare_SSL_files
#        steps:
#          - task: DownloadSecureFile@1
#            name: sslCert
#            displayName: 'Download cert'
#            inputs:
#              secureFile: 'example.crt'
#
#          - task: DownloadSecureFile@1
#            name: sslKey
#            displayName: 'Download key'
#            inputs:
#              secureFile: 'example.key'
#
#          - script: |
#              echo "$(whoami)"
#              sudo chown "$(whoami)":root $(sslCert.secureFilePath)
#              sudo chmod 600 $(sslCert.secureFilePath)
#              sudo chown "$(whoami)":root $(sslKey.secureFilePath)
#              sudo chmod 600 $(sslKey.secureFilePath)
#
#              TARGET_DIR="/home/$(whoami)/.ssl"
#              echo "TARGET_DIR: $TARGET_DIR"
#              mkdir -p "$TARGET_DIR"
#              sudo ln -s $(sslCert.secureFilePath) "$TARGET_DIR/example.crt"
#              sudo ln -s $(sslKey.secureFilePath) "$TARGET_DIR/example.key"
#              echo "files:"
#              ls -al "$TARGET_DIR"
#              #sudo chown "$(whoami)" "$TARGET_DIR"/*
#              #sudo chmod 600 "$TARGET_DIR"/*
#              #ls -al "$TARGET_DIR"
#              sudo chown -R "$(whoami)" "$TARGET_DIR"
#            displayName: 'Prepare SSL key and cert'

  - stage: Build
    jobs:
      - job: Build_Docker_Containers
        steps:
          - task: DownloadSecureFile@1
            name: sslCert
            displayName: 'Download cert'
            inputs:
              secureFile: 'example.crt'

          - task: DownloadSecureFile@1
            name: sslKey
            displayName: 'Download key'
            inputs:
              secureFile: 'example.key'

          - script: |
              echo "$(whoami)"
              sudo chown "$(whoami)":root $(sslCert.secureFilePath)
              sudo chmod 600 $(sslCert.secureFilePath)
              sudo chown "$(whoami)":root $(sslKey.secureFilePath)
              sudo chmod 600 $(sslKey.secureFilePath)

              TARGET_DIR="/home/$(whoami)/.ssl"
              echo "TARGET_DIR: $TARGET_DIR"
              mkdir -p "$TARGET_DIR"
              sudo ln -s $(sslCert.secureFilePath) "$TARGET_DIR/example.crt"
              sudo ln -s $(sslKey.secureFilePath) "$TARGET_DIR/example.key"
              #sudo cp $(sslCert.secureFilePath) "$TARGET_DIR/example.crt"
              #sudo cp $(sslKey.secureFilePath) "$TARGET_DIR/example.key"
              echo "files:"
              ls -al "$TARGET_DIR"
              #sudo chown "$(whoami)" "$TARGET_DIR"/*
              #sudo chmod 600 "$TARGET_DIR"/*
              #ls -al "$TARGET_DIR"
              sudo chown -R "$(whoami)" "$TARGET_DIR"
            displayName: 'Prepare SSL key and cert'

          - script: |
              #TARGET_DIR="/home/$(whoami)/.ssl"
              #ls -al "$TARGET_DIR"
              #bash .github/actions/runDockerE2E.sh
              export CERT_PATH="$HOME/.ssl/example"
              bash .github/actions/run_docker_e2e.sh "" "https"
            displayName: 'Build containers'

      - job: Run_Docker_Containers
        steps:
          - script: |
              docker-compose up -d
              sleep 30
              HOST_IP="$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)"
              RES="$(curl -s "https://$HOST_IP:8081/api/version")"
              echo "RES: $RES"
              [ "$RES" == "TODO" ]
            displayName: 'Run containers'

      - job: Run_E2E_Tests
        steps:
          - script: |
              npm run e2e -- --headless=false
            displayName: 'Run E2E Tests'
