# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

#pr: none

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: MyGitHub_splitman2run # The name used to reference this repository in the checkout step
      type: github
      endpoint: lezhumain
      name: lezhumain/SplitMan2-run

variables:
- group: var_groupe
- name: IMAGE
  value: splitman2
- name: SREPO
  value: SplitMan2

stages:
  - stage: Build
    jobs:
      - job: Build_Docker_Containers
        steps:
          - checkout: self
          - checkout: MyGitHub_splitman2run

          - task: DownloadSecureFile@1
            name: rsaGithub
            displayName: 'Download key'
            inputs:
              secureFile: 'id_devops'

          - task: NodeTool@0
            inputs:
              versionSource: 'spec'
              versionSpec: '20.x'

          - script: |
              if [ -z "$IMAGE" ]; then
                exit 1
              fi
            displayName: 'Test variables'

          - script: |
              cd "$SREPO"
              chmod +x install_ssh_eky.sh
              sudo cp "$SSH_KEY" ./id_rsa # TODO remove me
              ./install_ssh_eky.sh
            env:
              HOST_IP: $(DEBIAN_IP)
              SSH_KEY: $(rsaGithub.secureFilePath)
            displayName: 'Add SSH priv key to agent'

          - script: |
              cd "$SREPO"
              bash ../SplitMan2-run/run_docker_e2e.sh "https" "$SREPO"
              docker save "$IMAGE" -o "$(Build.ArtifactStagingDirectory)/$IMAGE.tar"
              echo "Saved tar:"
              ls -ald "$(Build.ArtifactStagingDirectory)/$IMAGE.tar"
            env:
              HOST_IP: $(DEBIAN_IP)
              SSH_KEY: $(rsaGithub.secureFilePath)
            displayName: 'Build containers'

          - script: |
              cp "SplitMan2-run/prepare_azure_ssh.sh" "$(Build.ArtifactStagingDirectory)/"
              cp "SplitMan2-run/setup_azure_ssh.sh" "$(Build.ArtifactStagingDirectory)/"
              echo "Saved scripts"
              ls -alh "$(Build.ArtifactStagingDirectory)/"
            displayName: 'Copy SSH script to artifacts'

          - publish: '$(Build.ArtifactStagingDirectory)/$(IMAGE).tar'
            displayName: 'Publish tar image'
            artifact: $(IMAGE)_tar

          - publish: '$(Build.ArtifactStagingDirectory)/prepare_azure_ssh.sh'
            displayName: 'Publish prepare script'
            artifact: prepare_azure_ssh

          - publish: '$(Build.ArtifactStagingDirectory)/setup_azure_ssh.sh'
            displayName: 'Publish SSH script'
            artifact: setup_azure_ssh
