FROM node:20-alpine AS build

RUN apk add chromium

WORKDIR /app

RUN npm cache clean --force
COPY . .
RUN npm ci --force

ARG IP
RUN echo "npm run e2e -- --headless=true --host=\"$IP\" --docker=true" > /app/run.sh
CMD ["sh", "./run.sh"]
