#FROM ubuntu:latest
FROM debian:buster

RUN apt update && apt install -y dos2unix vim jq curl default-jdk unzip zip

RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt install -y nodejs

WORKDIR /app

COPY ./prepare_android.sh .
COPY cordova_react_test.zip .
COPY ./buildCordovaApp.sh .
COPY ./dist /app/dist

RUN chmod +x /app/*.sh && dos2unix /app/*.sh

RUN mkdir /app/tmp && cd /app/tmp && unzip ../cordova_react_test.zip && dos2unix cordova_react_test/*.sh \
    && chmod +x cordova_react_test/*.sh && zip -r ../cordova_react_test.zip cordova_react_test

RUN bash /app/prepare_android.sh \
    && export PATH="$PATH:$(cat /path_add_1):$(cat /path_add_2)" && export ANDROID_HOME="/root/android/sdk" \
    && chmod +x /app/buildCordovaApp.sh && dos2unix /app/buildCordovaApp.sh \
    && bash /app/buildCordovaApp.sh "SplitMan2"

# docker build -t splitman2androidall -f Dockerfile_android_3 .
