FROM node:20-alpine AS build

RUN apk add chromium

RUN apk --update add openssh-client
RUN apk add git

WORKDIR /app

RUN npm cache clean --force
COPY . .
RUN chmod +x ./install_ssh_eky.sh \
    && sh ./install_ssh_eky.sh
RUN npm ci --force

ARG IP
RUN echo "npm run e2e -- --headless=true --host=\"$IP\" --docker=true" > /app/run.sh
CMD ["sh", "./run.sh"]
