#FROM ubuntu:latest
#FROM debian:buster

#RUN apt update && apt install -y dos2unix vim jq curl default-jdk unzip zip

FROM eclipse-temurin:17-jdk-jammy

RUN apt update && apt install -y dos2unix vim jq curl unzip zip

RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
#RUN apt-get update && \
#    apt-get install -y ca-certificates curl gnupg && \
#    mkdir -p /etc/apt/keyrings && \
#    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
#    NODE_MAJOR=18; echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
#    apt-get update
RUN apt install -y nodejs

WORKDIR /app

COPY ./prepare_android.sh .

RUN chmod +x /app/*.sh && dos2unix /app/*.sh

RUN bash /app/prepare_android.sh

#docker build -t splitman2androidbase -f Dockerfile_android .

CMD java --version && node -v && find / -name "path_add_*"
