name: Monthly Zenhub metrics
# dummy change
#on:
#  workflow_dispatch:
#  schedule:
#    - cron: '3 2 1 * *'

on: [pull_request]

jobs:
  build:
    name: pr metrics
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: "${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}"
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run zenhub-report-action tool
      uses: lezhumain/zenhub_report_action@better_reports_and_args
      with:
        WORKSPACE_ID: '5e3018c2d1715f5725d0b8c7'
        REPO_ID: '409231566'
        FROM_PIPELINE: 'Backlog'
        TO_PIPELINE: 'Awaiting TESS Review'
        FROM_DATE: ''
        TO_DATE: ''
      env:
        GH_TOKEN: ${{ github.token }}
        API_KEY: ${{ secrets.ZH_TOKEN }}

    - name: Check output file
      shell: bash
      run: |
        ls -alh ./zenhub_report.md
        du -sh ./zenhub_report.md

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v5
      with:
        title: Monthly zenhub metrics report
        content-filepath: ./zenhub_report.md
        assignees: ""
        labels: |
            report
        token: ${{ github.token }}
