name: Check puppeteer version

on: [pull_request]

defaults:
  run:
    working-directory: .

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Get current version
        run: |
          LAST_VERSION="$(curl -s https://api.github.com/repos/puppeteer/puppeteer/tags  | grep -Eo "\"v[^\"]+\"" | sed 's|"||g' | head -n 1)"
          CURRENT_VERSION="$(cat package.json | grep "puppeteer" | grep -Eo "\^[^\"]+" | sed 's|\^||')"
          echo "$LAST_VERSION"
          echo "$CURRENT_VERSION"
          #export VAR_TEST="exported"

          TARGET_STATUS="fail"
          if [ "$LAST_VERSION" == "v$CURRENT_VERSION" ]; then
            TARGET_STATUS="pass"
          fi
          echo "TARGET_STATUS=$TARGET_STATUS" >> $GITHUB_ENV

      - uses: emibcn/badge-action@v1.2.1
        with:
          label: 'Latest Puppeteer_${VAR_TEST}'
          status: "${{ env.TARGET_STATUS }}"
          color: 'blue,555,daf'
          path: '.github/badges/coverage.svg'

