name: Check puppeteer version

on: [pull_request]

defaults:
  run:
    working-directory: .

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Get current version
        run: |
          LAST_VERSION="$(curl -s https://api.github.com/repos/puppeteer/puppeteer/tags  | grep -Eo "\"v[^\"]+\"" | sed 's|"||g' | head -n 1)"
          CURRENT_VERSION="$(cat package.json | grep "puppeteer" | grep -Eo "\^[^\"]+" | sed 's|\^||')"
          echo "$LAST_VERSION"
          echo "$CURRENT_VERSION"
          export VAR_TEST="exported"

      - uses: emibcn/badge-action@v1.2.1
        with:
          label: 'Latest Puppeteer_${VAR_TEST}'
          status: '53.4%'
          color: 'blue,555,daf'
          path: '.github/badges/coverage.svg'

